# Generated by Django 4.2.5 on 2023-10-09 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_attempter_management', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mark',
            options={'ordering': ['-marks']},
        ),
    ]
