# Generated by Django 4.2.5 on 2023-10-10 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_attempter_management', '0003_alter_mark_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mark',
            options={'ordering': ['-obtained_mark']},
        ),
        migrations.RenameField(
            model_name='mark',
            old_name='marks',
            new_name='obtained_mark',
        ),
    ]
