# Generated by Django 4.2.5 on 2023-10-10 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_attempter_management', '0005_alter_mark_options_rename_obtained_mark_mark_marks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mark',
            options={'ordering': ['-mark']},
        ),
        migrations.RenameField(
            model_name='mark',
            old_name='marks',
            new_name='mark',
        ),
    ]
