
MAX_TEMP_INDEX = 0
MIN_TEMP_INDEX = 2
MAX_HUMIDITY_INDEX = 6
MIN_HUMIDITY_INDEX = 8
POSITIVE_INFINITY = float('+inf')
NEGATIVE_INFINITY = float('-inf')
HOTTEST_DAY = 0
HOTTEST_DAY_MONTH_IDX = 1
HOTTEST_DAY_DATE_INDEX = 2
HOTTEST_DAY_TEMPERATURE_INDEX = 3
TWENTY_LEFT_SPACES = 20
EIGHT_LEFT_SPACES = 8
TWELWE_LEFT_SPACES = 12
FIFTEEN_LEFT_SPACES = 15
TASKS = {
    'annual report': '1',
    'hottest day': '2'
}
MONTHLY_HOTTEST_DAY = 0
MONTHLY_HOTTEST_TEMP = 1
EMPTY = ""         
MAX_TEMPERATUES = 'max temperatures'
MIN_TEMPERATURES = 'min temperatures'
MAX_HUMIDITIES = 'max humidities'
MIN_HUMUDITIES = 'min humidities'
ANNUAL_REPORT_TASK = 'annual report'
HOTTEST_DAY_TASK = 'hottest day'
YEARLY_MAXIMUM_TEMPERATURE = 3
MONTHLY_HOTTEST_DAY = 0
MONTHLY_HOTTEST_DAY = 1
