SAFETY_MEASURE = 0
EFFICIENCY = 1
CASES_STATS = 'cases_stats'
SAFETY_MEASURES = 'safety_measures'
COUNTRY_NAME_IDX_IN_COVID_STATS = 0
COUNTRY_NAME_IDX_IN_COVID_SAFETY_MEASURES = 1
TOTAL_RECOVERED_PATIENTS = 5
TOTAL_PATIENTS = 1
IMPLEMENTED_SAFETY_MEASURES = 7
TOTAL_DEATHS = 3
EMPTY_STRING = ""
TOTAL_CASES = 1
ZERO = 0
COVID_FILES_PATH = "covid_files_path"
RECOVERED_RATIO = 'RECOVERED_RATIO'
SAFETY_MEASURE_ARG = 'SAFETY_MEASURE_ARG'
MOST_EFFICIENT_SAFETY_MEASURES = 'MOST_EFFICIENT_SAFETY_MEASURES'
GRAPHICAL_DISPLAY = 'GRAPHICAL_DISPLAY'
TASK_FLAGS = {
    RECOVERED_RATIO:'-a',
    SAFETY_MEASURE_ARG:'-b',
    MOST_EFFICIENT_SAFETY_MEASURES:'-c',
    GRAPHICAL_DISPLAY:'-d'
    }
