ADD_QUIZ_ATTEMPTER = 'quiz_management/add_quiz_attempter.html'
ADD_QUIZ_ATTEMPTER_URL = '/quiz-management/add-quiz-attempter'
ADD_QUIZ_PAGE = 'quiz_management/add_quiz.html'
ADD_QUIZ_SUCCESS_MESSAGE = "Quiz Added Successfully"
ADD_QUESTION_PAGE = 'quiz_management/add_question.html'
ADD_QUESTION_URL = '/quiz-management/question'
ANSWER = 'answer'
ANNOUNCEMENT_DONE_MSG = "Announcement Done"
ANNOUNCEMENT_PAGE = 'quiz_management/announcement.html'
APPROVE_HOST = 'hosts_to_approve'
BOOLEAN = "boolean"
BOOLEAN_QUESTION_ADDED_SUCCESSFULLY_MSG = "Boolean Question Added Successfully!"
BROWSE_QUESTION_URL = '/quiz-management/browse-questions'
CAGTEGORY = 'category'
DETAILS = 'details'
DRAFT_QUIZZES_PAGE = 'quiz_management/draft_quizzes.html'
EDIT_DRAFT = '/quiz-management/edit-draft'
EMAIL = 'email'
EMAILS = 'emails'
END_TIME = 'end_time'
HOST_MANAGEMENT_PAGE = 'quiz_management/host_management.html'
IS_PUBLIC = 'is_public'
MARKS = 'marks'
MCQS = "mcq"
MCQS_ADDED_SUCCESSFULLY_MSG = "MCQ added successfully!"
OPTION_1 = 'option_1'
OPTION_2 = 'option_2'
OPTION_3 = 'option_3'
OPTION_4 = 'option_4'
PASSWORD = "namal123"
POST = "POST"
PUBLIC_QUESTION_ADDED_MSG = 'question added'
PUBLIC_QUESTIONS_PAGE = 'quiz_management/public_questions.html'
QUESTION_TITLE = 'question_title'
QUIZ_DRAFT_PAGE = 'quiz_management/quiz_draft.html'
QUIZ_MANAGEMENT_HOMEPAGE = 'quiz_management/quiz_management.html'
REPORT_PAGE = 'quiz_management/report.html'
START_TIME = 'start_time'
STUDENT_EMAIL_FILE = 'students_emails_file'
SUBJECT = 'subject'
SUBJECTIVE = "subjective"
SUBJECTIVE_QUESTION_ADDED_SUCCESSFULLY_MSG = "Subjective Question Added Successfully!"
TITLE = 'title'
TYPE = 'type'
