# Generated by Django 4.2.5 on 2023-10-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_management', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuizAttemptersExcel',
        ),
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ManyToManyField(related_name='questions', to='quiz_management.quiz'),
        ),
    ]
