ALERT_DANGER = "alert alert-danger"
ALERT_SUCCESS = "alert alert-success"
ANNOUNCEMENT_PAGE = 'quiz_attempter_management/announcements.html'
ANSWERS = "answers"
ATTEMPT_QUIZZ_PAGE = "quiz_attempter_management/attempt_quiz.html"
ATTEMPT_QUIZZ_URL = '/quiz-attempter-homepage/attempt-quiz'
BOOLEAN = 'boolean'
COMMENT = 'comment'
CORRECT_ANSWER = 'is_correct_answer'
DETAILS = 'details'
DISCUSSION_PAGE = 'quiz_attempter_management/discussion.html'
FULL_DISCUSSION_PAGE = 'quiz_attempter_management/full_discussion.html'
MARKS_PAGE = 'quiz_attempter_management/marks.html'
MARKS_URL = '/quiz-attempter-homepage/marks'
MCQS = "mcq"
POST = "POST"
QUIZ_ATTEMPTER_PROFILE_PAGE = 'quiz_attempter_management/profile.html'
QUIZZES_PAGE = 'quiz_attempter_management/show_quizzes.html'
QUESTION_TITLE = 'question_title'
SUBJECT = 'subject'
SUBJECTIVE = "subjective"
START_DISCUSSION_PAGE = 'quiz_attempter_management/start_discussion.html'
TYPE = 'type'
VIEW_DISCUSSION_PAGE = 'quiz_attempter_management/view_discussion.html'
